const ON_LOAD = "ON_LOAD";
const OFF_LOAD = "OFF_LOAD";
const SET_USERS = "SET_USERS";
const SET_POSTS = "SET_POST";
const SET_FILTER = "SET_FILTER";

export {
  OFF_LOAD,
  ON_LOAD,
  SET_POSTS,
  SET_USERS,
  SET_FILTER
}
